differentiation between the studies for authorization
PM4Onco/fhirspark pull request #133
Opened 2021-04-21 11:11 UTC by chrisHub957

The studyId parameter from the incoming request is now used to differentiate from which study the user is requesting the patient.
This is only working if the studyId gets appended to the request by the frontend  https://github.com/nr23730/cbioportal-frontend/pull/57

## Reviewer
@nr23730

2021-04-22 07:23 UTC, nr23730 commented
This is a pretty nice approach that I didn't think of. Thank you for that.
However as the studyId parameter is not used anymore I would like to remove it from the codebase.

2021-04-22 14:22 UTC, chrisHub957 commented
what exactly do you mean with the studyId parameter is not used anymore?

2021-04-23 13:34 UTC, nr23730 requested changes

2021-04-23 13:34 UTC, nr23730 commented on src/main/java/fhirspark/FhirSpark.java
> -        String validatePath = "api/studies/" + settings.getMtbStudy() + "/patients/"
The parameter `settings.getMtbStudy()` is not used anymore, so why don't you remove it?

2021-04-23 13:34 UTC, nr23730 commented on src/main/java/fhirspark/FhirSpark.java
> -        String mtbStudy = settings.getMtbStudy();
Same goes for this one.

2021-04-23 13:35 UTC, nr23730 commented
> what exactly do you mean with the studyId parameter is not used anymore?

I marked the specific lines in the code. Apart from that this looks just fine.

2021-04-23 14:17 UTC, chrisHub957 commented
> 
> 
> > what exactly do you mean with the studyId parameter is not used anymore?
> 
> I marked the specific lines in the code. Apart from that this looks just fine.

oh you mean the specific MTB-Study ID from the settings, sorry I got a little confused there ;) Yes that can be removed now...

2021-04-23 14:40 UTC, nr23730 approved these changes

2021-04-23 14:46 UTC, merged