Follow up addition
PM4Onco/fhirspark pull request #253
Opened 2022-06-30 13:21 UTC by BoehmDo

Adds the capabilities and data structures for handling therapyRecommendation followup data from cbioportal.

2022-06-30 13:50 UTC, BoehmDo commented
Sorry, i just found some more missing pieces and bugs. I will push a fix shortly, so you don't have to bother testing yet.

2022-06-30 13:55 UTC, nr23730 commented
Okay, I set this as draft for now, just mark it as ready for review when you figured out what's wrong. 
Also: Where is the frontend for testing this?

2022-06-30 14:24 UTC, BoehmDo commented
Should be all fixed now!
https://github.com/nr23730/cbioportal-frontend/pull/84 And this is the corresponding frontend change.

2022-06-30 17:35 UTC, nr23730 requested changes
First: Kudos for making this happen and wrapping your head around this.

There is some minor coding style stuff and a wrong usage of a VS/CS.
To be honest: Using the note field for the therapy response is a nicely working idea, but lacks some semantics. I'd like to encourage you to take a look at the LOINC code [88040-1](https://loinc.org/88040-1/) and it's answer list [LL4721-8](https://loinc.org/88040-1/). 
The corresponding timings could then be set using the `effective[x]` attribute of the `Observation` resource.
 
(cc: @Unberath)

2022-06-30 17:35 UTC, nr23730 commented on Dockerfile
> +COPY hgnc.csv /app/
This should not be contained in the final release as it just blows up the docker container.

2022-06-30 17:35 UTC, nr23730 commented on src/main/java/fhirspark/adapter/FollowUpAdapter.java
> +    private static String mtbUri;
Not used

2022-06-30 17:35 UTC, nr23730 commented on src/main/java/fhirspark/adapter/FollowUpAdapter.java
> +    private static String serviceRequestUri;
Not used

2022-06-30 17:35 UTC, nr23730 commented on src/main/java/fhirspark/restmodel/CbioportalRest.java
> +    @JsonProperty("mtbs")
I think this should be `followUps`.

2022-06-30 17:35 UTC, nr23730 commented on src/main/resources/settings.yaml
> +portalUrl: ${FHIRSPARK_PORTALURL:-http://localhost:8080/fhir/}
Why is this changed? This URL should point to cBioPortal and it looks like it is not being used in your codebase anyway.

2022-06-30 17:35 UTC, nr23730 commented on src/main/resources/settings.yaml
> +fhirDbBase: ${FHIRSPARK_FHIRBASE:-http://localhost:8080/fhir/}
I intentionally removed the `/` because otherwise some FHIR servers like blaze might return a `308 Permanently moved` status code.

2022-06-30 17:35 UTC, nr23730 commented on src/main/java/fhirspark/adapter/FollowUpAdapter.java
> +                responseObs.addIdentifier().setSystem("https://cbioportal.org/followUpResponse/")
I'd like to see this moved to an enum or at least to a static constant of the class.

2022-06-30 17:35 UTC, nr23730 commented on src/main/java/fhirspark/adapter/FollowUpAdapter.java
> +            coding.setSystem("http://hl7.org/fhir/ValueSet/reason-medication-status-codes");
This is wrong. `reason-medication-status-codes` describes a value set, the corresponding code is from SNOMED CT, so the system would be `http://snomed.info/sct`.

2022-07-24 09:53 UTC, BoehmDo commented
First of all, thanks again for all the helpful pointers. :) I have reworked the response observations with the suggested Loinc codes and combined with the best response guarantee from the frontend the structure looks and feels much cleaner now. The hardcoded Systems have all been moved to enums. 
Also all of the small changes that have been made to the settings and dockerfiles have been removed. Those were  remainders of attempted bugfixes that i didn't properly revert. I'm going to keep those out of future PRs!

2022-08-02 12:22 UTC, nr23730 requested changes
Well done! The codebase looks now much cleaner and maintainable.
Also moving the Response codes to LOINC is a huge benefit in interoperability. 

However, when testing nr23730/cbioportal-frontend#84 I came across an issue that I described there. This should be resolved, then from my side there is nothing stopping this from being merged.

(cc: @Unberath)

2022-08-05 12:43 UTC, nr23730 approved these changes
Now this is working like a charm! Thank you very much!

2022-08-05 13:39 UTC, nr23730 requested changes
I just merge the current master into it, that has all tests fixed. I realized, that querying the clinical data attributes does not work anymore. This would be a blocker from by side.

(cc: @Unberath)

2022-08-09 13:29 UTC, nr23730 approved these changes

2022-08-09 13:29 UTC, merged

2022-08-09 13:33 UTC, BoehmDo commented
Hopefully everything is fixed now. Also, it seems like there is an Issue in the interaction with the Hapi server v6.2.0, where the specimen Resources that are linked within the ClinicalData Observations are not being created and/or referenced. This currently does not break tests and fails silently. This does not occur with neither v6.0.1 nor v5.7.0.

2022-08-09 14:13 UTC, nr23730 commented
Thank you very much for fixing this. Well there is also no official docker image for HAPI 6.2.0 - I wonder why. ;)